name: ci

on:
  push:

jobs:
  my_job: # job_id or job_name change as per your choice
    name: build # job name change as per your choice
    runs-on: ubuntu-22.04 # runner type change as per your choice os

    steps: # steps to run the job
      - uses: actions/checkout@v4 # checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Node # step name change as per your choice
        uses: actions/setup-node@v4 # sets up a node environment for use in actions by adding it to the PATH and optionally caching npm modules
        with:
          node-version: "24.13" # node version change as per your choice

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/9492925563/github-action-demo:${{ github.sha }} .
      - name: Push image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push docker.io/9492925563/github-action-demo:${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'docker.io/9492925563/github-action-demo:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
